services:
  spuc:
    build:
      context: ./SPUC-Stats
      dockerfile: Dockerfile
    container_name: spuc_container
    volumes:
      - ./SPUC-Stats/print.config:/spuc/config/print.config
      - spuc-volume:/spuc/output
      - ./SPUC-Stats/stats.py:/spuc/plugins/stats.py
    environment:
      - EXPORT=true
    command: [ "--units", "iulu" ]
    networks:
      - spuc_network
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://spuc:8321/export" ]
      interval: 3s
      timeout: 2s
      retries: 5

  spucsvi:
    image: spuacv/spucsvi:latest
    container_name: spucsvi
    ports:
      - "8322:8322"
    environment:
      - SPUC_URL=http://spuc:8321
    networks:
      - spuc_network
    depends_on:
      spuc:
        condition: service_healthy

volumes:
  spuc-volume:


networks:
  spuc_network:
    name: spuc_network
